src/SupportApp/Controllers/RequestTypesController.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data.SqlClient;
using System.Linq;
using System.Threading.Tasks;
using DNTBreadCrumb.Core;
using DNTCommon.Web.Core;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using SupportApp.Common.GuardToolkit;
using SupportApp.Common.IdentityToolkit;
using SupportApp.Services.Contracts;
using SupportApp.Services.Identity;
using SupportApp.ViewModels;
using SupportApp.ViewModels.Identity;

namespace SupportApp.Controllers
{
    [Authorize(Policy = ConstantPolicies.DynamicPermission)]
    [BreadCrumb(UseDefaultRouteUrl = true, Order = 0)]
    [DisplayName("مدیریت نوع درخواست ها")]
    public class RequestTypesController : Controller
    {
        private const string RequestTypeNotFound = "نوع درخواست درخواستی یافت نشد.";
        private const int DefaultPageSize = 7;

        private readonly IRequestTypeService _requestTypeService;

        public RequestTypesController(IRequestTypeService requestTypeService)
        {
            _requestTypeService = requestTypeService;
            _requestTypeService.CheckArgumentIsNull(nameof(_requestTypeService));
        }

        [BreadCrumb(Title = "ایندکس", Order = 1)]
        [DisplayName("ایندکس")]
        public async Task<IActionResult> Index()
        {
            var requestTypeViewModels = await _requestTypeService.GetAllAsync();
            return View(requestTypeViewModels);
        }

        [AjaxOnly]
        [DisplayName("نمایش فرم نوع درخواست ها")]
        public async Task<IActionResult> RenderRequestType([FromBody]ModelIdViewModel model)
        {
            if (string.IsNullOrWhiteSpace(model?.Id))
            {
                return PartialView("_Create", new RequestTypeViewModel());
            }

            var requestTypeViewModel = await _requestTypeService.GetByIdAsync(Convert.ToInt32(model.Id));
            if (requestTypeViewModel == null)
            {
                ModelState.AddModelError("", RequestTypeNotFound);
                return PartialView("_Create");
            }

            return PartialView("_Create", requestTypeViewModel);
        }

        [AjaxOnly]
        [HttpPost]
        [ValidateAntiForgeryToken]
        [DisplayName("ویرایش نوع درخواست")]
        public async Task<IActionResult> EditRequestType(RequestTypeViewModel viewModel)
        {
            if (ModelState.IsValid)
            {
                var requestTypeViewModel = await _requestTypeService.GetByIdAsync(viewModel.Id);
                if (requestTypeViewModel == null)
                {
                    ModelState.AddModelError("", RequestTypeNotFound);
                }
                else
                {
                    var result = await _requestTypeService.UpdateAsync(viewModel);
                    if (result)
                    {
                        return Json(new { success = true });
                    }

                    ModelState.AddModelError("", RequestTypeNotFound);
                }
            }

            return PartialView("_Create", model: viewModel);
        }

        [AjaxOnly]
        [HttpPost]
        [ValidateAntiForgeryToken]
        [DisplayName("ایجاد یک نوع درخواست جدید")]
        public async Task<IActionResult> AddRequestType(RequestTypeViewModel viewModel)
        {
            if (ModelState.IsValid)
            {
                var result = await _requestTypeService.InsertAsync(viewModel);
                if (result)
                {
                    return Json(new { success = true });
                }

                ModelState.AddModelError("", RequestTypeNotFound);
            }

            return PartialView("_Create", model: viewModel);
        }

        [AjaxOnly]
        [DisplayName("نمایش فرم حذف نوع درخواست")]
        public async Task<IActionResult> RenderDeleteRequestType([FromBody]ModelIdViewModel model)
        {
            if (string.IsNullOrWhiteSpace(model?.Id))
            {
                return PartialView("_Delete");
            }

            var requestTypeViewModel = await _requestTypeService.GetByIdAsync(Convert.ToInt32(model.Id));
            if (requestTypeViewModel == null)
            {
                ModelState.AddModelError("", RequestTypeNotFound);
                return PartialView("_Delete");
            }

            if (await _requestTypeService.CheckExistRelationAsync(requestTypeViewModel.Id))
            {
                ModelState.AddModelError("", RequestTypeNotFound);
                return PartialView("_Used");
            }

            return PartialView("_Delete", model: requestTypeViewModel);
        }

        [AjaxOnly]
        [HttpPost]
        [ValidateAntiForgeryToken]
        [DisplayName("حذف نوع درخواست")]
        public async Task<IActionResult> Delete(RequestTypeViewModel viewModel)
        {
            var requestTypeViewModel = await _requestTypeService.GetByIdAsync(viewModel.Id);
            if (requestTypeViewModel == null)
            {
                ModelState.AddModelError("", RequestTypeNotFound);
            }
            else
            {
                var result = await _requestTypeService.DeleteAsync(requestTypeViewModel.Id);
                if (result)
                {
                    return Json(new { success = true });
                }

                ModelState.AddModelError("", RequestTypeNotFound);
            }

            return PartialView("_Delete", model: viewModel);
        }
    }
}

src/SupportApp/Views/RequestTypes/Index.cshtml
@model IEnumerable<RequestTypeViewModel>

@{
    ViewData["Title"] = "مدیریت نوع درخواست ها";
}

<partial name="_Used" />

<div class="card mt-5">
    <div class="card-header">
        <h5 class="card-title">@ViewData["Title"]</h5>
    </div>
    <div class="card-body">
        <partial name="_List" model="Model" />
    </div>
    <footer class="card-footer">
        
        <security-trimming asp-area="" asp-controller="RequestTypes" asp-action="RenderRequestType">
            <a class="btn btn-success" href="#" id="btnCreate">ایجاد یک نوع درخواست جدید</a>
        </security-trimming>
    </footer>
</div>

@section Scripts
{
    <script type="text/javascript">
        $(function () {
            $('#btnCreate').click(function (e) {
                e.preventDefault(); //می‌خواهیم لینک به صورت معمول عمل نکند

                $.bootstrapModalAjaxForm({
                    postUrl: '@Url.Action("AddRequestType", "RequestTypes")',
                    renderModalPartialViewUrl: '@Url.Action("RenderRequestType", "RequestTypes")',
                    renderModalPartialViewData: {},
                    loginUrl: '/identity/login',
                    beforePostHandler: function () {
                    },
                    completeHandler: function () {
                        location.reload();
                    },
                    errorHandler: function () {
                    }
                });
            });

            $("a[id^='btnEdit']").click(function (e) {
                e.preventDefault(); //می‌خواهیم لینک به صورت معمول عمل نکند
                var requestTypeId = $(this).data("edit-id");

                $.bootstrapModalAjaxForm({
                    postUrl: '@Url.Action("EditRequestType", "RequestTypes")',
                    renderModalPartialViewUrl: '@Url.Action("RenderRequestType", "RequestTypes")',
                    renderModalPartialViewData: JSON.stringify({ "id": requestTypeId }),
                    loginUrl: '/identity/login',
                    beforePostHandler: function () {
                    },
                    completeHandler: function () {
                        location.reload();
                    },
                    errorHandler: function () {
                    }
                });
            });

            $("a[id^='btnDelete']").click(function (e) {
                e.preventDefault(); //می‌خواهیم لینک به صورت معمول عمل نکند
                var requestTypeId = $(this).data("delete-id");

                $.bootstrapModalAjaxForm({
                    postUrl: '@Url.Action("Delete", "RequestTypes")',
                    renderModalPartialViewUrl: '@Url.Action("RenderDeleteRequestType", "RequestTypes")',
                    renderModalPartialViewData: JSON.stringify({ "id": requestTypeId }),
                    loginUrl: '/identity/login',
                    beforePostHandler: function () {
                    },
                    completeHandler: function () {
                        location.reload();
                    },
                    errorHandler: function () {
                    }
                });
            });
        });
    </script>
}

src/SupportApp/Views/RequestTypes/_Create.cshtml
@model RequestTypeViewModel
<partial name="_CustomValidationSummary" />
<form asp-action="AddRequestType" method="post">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                @if (Model.Id == 0)
                {
                    <h4 class="modal-title">ایجاد یک نوع درخواست جدید</h4>
                }
                else
                {
                    <h4 class="modal-title">ویرایش یک نوع درخواست</h4>
                }
            </div>
            <div class="modal-body">
                <div class="form-group row">
                    <label asp-for="Name" class="col-md-3 col-form-label text-md-left"></label>
                    <div class="col-md-9">
                        <input asp-for="Id" />
                        <input dir="rtl" asp-for="Name" class="form-control" />
                        <span asp-validation-for="Name" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group row">
                    <label asp-for="Description" class="col-md-3 col-form-label text-md-left"></label>
                    <div class="col-md-9">
                        <textarea dir="rtl" asp-for="Description" class="form-control"></textarea>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                @if (Model.Id == 0)
                {
                    <security-trimming asp-area="" asp-controller="RequestTypes" asp-action="AddRequestType">
                        <button class="btn btn-primary" type="submit">ثبت</button>
                    </security-trimming>
                }
                else
                {
                    <security-trimming asp-area="" asp-controller="RequestTypes" asp-action="EditRequestType">
                        <button class="btn btn-primary" type="submit">ثبت</button>
                    </security-trimming>
                }
                <button class="btn" data-dismiss="modal" aria-hidden="true">انصراف</button>
            </div>
        </div>
    </div>
</form>

src/SupportApp/Views/RequestTypes/_Delete.cshtml
@model RequestTypeViewModel
<partial name="_CustomValidationSummary" />
<form asp-action="Delete" method="post" class="form-horizontal">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                <h4 class="modal-title">حذف یک نوع درخواست</h4>
            </div>
            <div class="modal-body">
                <span class="text-center">
                    آیا می‌خواهید نوع درخواست
                    <strong>@Model.Name</strong>
                    را حذف کنید؟
                </span>
                <input asp-for="Id" />
            </div>
            <div class="modal-footer">
                <security-trimming asp-area="" asp-controller="RequestTypes" asp-action="Delete">
                    <button class="btn btn-danger" type="submit">تائید حذف</button>
                </security-trimming>
                <button class="btn" data-dismiss="modal" aria-hidden="true">انصراف</button>
            </div>
        </div>
    </div>
</form>

src/SupportApp/Views/RequestTypes/_List.cshtml
@model IEnumerable<RequestTypeViewModel>

<div class="table-responsive">
  <table id="all-roles-list" class="table table-striped table-hover table-bordered">
   <thead class="thead-light">
    <tr>
        <th class="text-center">نام کاربری</th>
        <th class="text-center">توضیحات</th>
        <th class="text-center w-25">عملیات</th>
    </tr>
   </thead>
   <tbody>
    @if (!Model.Any())
            {
        <tr>
            <td colspan="3" class="text-center">هیچ دیتایی یافت نشد</td>
        </tr>
    }
    else
    {
        foreach (var item in Model)
        {
            <tr>
                <td class="text-center">@item.Name</td>
                <td class="text-center">@item.Description</td>
                <td class="text-center">
                    <security-trimming asp-area="" asp-controller="RequestTypes" asp-action="RenderRequestType">
                        <a href="#" id="btnEdit-@item.Id" data-edit-id="@item.Id" class="btn btn-sm btn-primary">ویرایش</a>
                    </security-trimming>
                    <security-trimming asp-area="" asp-controller="RequestTypes" asp-action="RenderDeleteRequestType">
                        <a href="#" id="btnDelete-@item.Id" data-delete-id="@item.Id" class="btn btn-sm btn-danger">حذف</a>
                    </security-trimming>
                </td>
            </tr>
        }
    }
  </tbody>
 </table>
</div>